### ISSUE TITLE
can not found my_global.h on configure

### ISSUE THREAD

**Issue by Joungkyun** [Joungkyun/lib_mysqludf_aes256#4]
If mysql prefix is not /usr, can not found my_global.h

``` bash
[root@host lib_mysqludf_aes256-1.0.3]$ ./configure --with-mysql=/opt/mysql-5.5.40
...
checking mysql.h usability... yes
checking mysql.h presence... yes
checking for mysql.h... yes
checking my_global.h usability... no
checking my_global.h presence... no
checking for my_global.h... no
configure: error: You must need my_global.h file to build this udf.
```

This issue is reported at https://oops.org/SERVICE/jsboard/read.php?table=jsboard_oopsQnA&no=53450 by 김대홍 &lt;srpro3 AT paran.com&gt;

**Comment by AntoineBouquetSully** [comment]
Hi, what's the solution to that ?

I have the same problem but with using /opt as mysql prefix

`./configure --with-mysql=/usr --with-mysql-config=/usr/bin/mysql_config`

**Comment by Joungkyun** [comment]
Hi, @AntoineBouquetSully 

What is your build environment?
Sorry, but there is nothing I can refer to for answers or corrections.

- mysql or mariadb version
- mysql installation location or prefix
- lib_mysqludf_ase256 version
- Build os and version
- and so on...
 
This issue has been closed. Please register as a new issue and leave this issue as a reference link. 

> Hi, what's the solution to that ?
> 
> I have the same problem but with using /opt as mysql prefix
> 
> `./configure --with-mysql=/usr --with-mysql-config=/usr/bin/mysql_config`

**Comment by AntoineBouquetSully** [comment]
Hi, thanks for your answer.

Sorry I may have posted this question too quickly because I thank that it was unresolved.
I tried to use your lib in a MariaDB docker container (version 10.4) but I did not succeed, this docker image lacks of some .h files needed.

After that I succeeded to use your librairy in a standalone server with MariaDB installed properly.
